CREATE DATABASE proj_final_mod3;

DROP TABLE alocacoes_prof;
DROP TABLE equipe;
DROP TABLE modulos;
DROP TABLE turmas;
DROP TABLE rel_mod_curso;

SELECT * FROM equipe;
SELECT * FROM turmas;


#qtd profs tech disponível
select equipe.MATRICULA FROM
equipe LEFT JOIN turma
on turma.MATRICULA_TECH = equipe.MATRICULA
where turma.DATA_FIM < curdate() AND equipe.DATA_SAIDA IS NULL;

CREATE TABLE equipe (
MATRICULA INT,
DATA_SAIDA DATE,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE cursos (
ID_CURSO INT,
NOME VARCHAR(50),
DESCRICAO VARCHAR(150),
VALOR INT,
DURACAO INT,
PRIMARY KEY (ID_CURSO)
);

CREATE TABLE modulos (
ID_MODULO INT,
NOME VARCHAR(50),
DESCRICAO VARCHAR(150),
DURACAO INT,
PRIMARY KEY (ID_MODULO)
);

CREATE TABLE turmas (
ID_TURMA INT,
MATRICULA_TECH INT,
DATA_FIM DATE,
PRIMARY KEY (ID_TURMA),
FOREIGN KEY (MATRICULA_TECH) REFERENCES equipe(MATRICULA)
);

CREATE TABLE alocacoes_prof (
INDICE INT,
MATRICULA INT,
ID_MODULO INT,
PRIMARY KEY (INDICE),
FOREIGN KEY (ID_MODULO) REFERENCES modulos(ID_MODULO),
FOREIGN KEY (MATRICULA) REFERENCES equipe(MATRICULA)
);

CREATE TABLE rel_mod_curso (
INDICE INT,
ID_CURSO INT,
ID_MODULO INT,
PRIMARY KEY (INDICE),
FOREIGN KEY (ID_CURSO) REFERENCES cursos(ID_CURSO),
FOREIGN KEY (ID_MODULO) REFERENCES modulos(ID_MODULO)
);